version: '3.8'

services:
  spring-backend:
    build: .
    container_name: spring-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://3.95.66.195:3306/properties?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MariaDBDialect
    ports:
      - "8080:8080"
    networks:
      - app_network

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "443:443"
    depends_on:
      - spring-backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
